# Generated by Django 5.1.2 on 2024-10-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_member_death_date_member_family_lastname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="children_num",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="member",
            name="death_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="father_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="mother_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
