# Generated by Django 5.1.2 on 2024-11-02 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0006_remove_member_is_alive"),
    ]

    operations = [
        migrations.RenameField(
            model_name="member",
            old_name="family_lastname",
            new_name="family_name",
        ),
    ]
