# Generated by Django 5.1.2 on 2024-11-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0007_rename_family_lastname_member_family_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="birth_date",
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="death_date",
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
