# Generated by Django 5.1.2 on 2024-11-11 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0009_member_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="father_id",
        ),
        migrations.RemoveField(
            model_name="member",
            name="mother_id",
        ),
        migrations.AddField(
            model_name="member",
            name="father",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children_father",
                to="members.member",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="mother",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children_mother",
                to="members.member",
            ),
        ),
    ]
