# Generated by Django 5.1.2 on 2024-11-16 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0010_remove_member_father_id_remove_member_mother_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MartialRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("married", models.BooleanField(default=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="martialrelationship",
                        to="members.member",
                    ),
                ),
                (
                    "spouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spouse_relationships",
                        to="members.member",
                    ),
                ),
            ],
        ),
    ]
