# Generated by Django 5.1.2 on 2024-12-14 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0011_martialrelationship"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="cached_age",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
